### ISSUE TITLE
Grant type password error

### ISSUE THREAD

**Issue by Michele404** [weeco/fortnite-client#19]
I got grant type password authorization error during the call of stats endpoint. It was working since 2h ago and now not

**Comment by weeco** [comment]
Fixed by a PR submitted by @qm42 . I'll publish the updated NPM library in a bit

**Comment by SkYNewZ** [comment]
Hello! I also have this error (https://github.com/SzymonLisowiec/node-epicgames-client/issues/15 or https://github.com/qlaffont/fortnite-api/issues/152). So I try to checkout this repo and direct use (with `/Users/quentin/Sources/fortnite-client/lib`) but I still get the `errors.com.epicgames.common.oauth.unauthorized_client` error. Any idea ?

I tried to add `User-Agent => "Fortnite/++Fortnite+Release-7.01-CL-4644078 IOS/11.3.1"` but nothing change 😬

[![asciicast](https://asciinema.org/a/273123.svg)](https://asciinema.org/a/273123)
